# Generated by Django 4.0.2 on 2022-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='annotation',
            field=models.TextField(verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
