# Generated by Django 4.0.2 on 2022-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categories_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/img/news_img/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
