# Generated by Django 4.0.2 on 2022-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
