# Generated by Django 4.0.2 on 2022-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='URL изображения'),
        ),
    ]
