# Generated by Django 4.0.2 on 2022-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=150, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='education',
            name='place_of_study',
            field=models.CharField(max_length=150, verbose_name='Место учебы'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='link_value',
            field=models.CharField(max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_link_name',
            field=models.CharField(max_length=150, verbose_name='Название социальной сети'),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='company',
            field=models.CharField(max_length=150, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Обязанности'),
        ),
    ]
