# Generated by Django 4.0.2 on 2022-02-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-date_of_admission'], 'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'ordering': ['id'], 'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='workexperiance',
            options={'ordering': ['-date_of_employment'], 'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
    ]
